/**
 * PDF Export Utility for Lulu Intelligence Dashboard
 * Uses jsPDF and jsPDF-AutoTable for professional PDF generation
 */

// @ts-ignore - jspdf types
import { jsPDF } from 'jspdf';
// @ts-ignore - jspdf-autotable types
import autoTable from 'jspdf-autotable';

interface KPIData {
  label: string;
  value: string | number;
  change?: string;
}

interface TableData {
  headers: string[];
  rows: (string | number)[][];
}

interface ChartImageData {
  title: string;
  imageData: string; // base64
  width?: number;
  height?: number;
}

export interface PDFExportOptions {
  title: string;
  subtitle?: string;
  dateRange?: string;
  kpis?: KPIData[];
  tables?: { title: string; data: TableData }[];
  charts?: ChartImageData[];
  footer?: string;
}

// Lulu brand colors
const COLORS = {
  primary: [220, 38, 38], // Red
  secondary: [30, 41, 59], // Slate
  accent: [6, 182, 212], // Cyan
  text: [15, 23, 42],
  lightText: [100, 116, 139],
  background: [248, 250, 252],
};

export const generatePDF = async (options: PDFExportOptions): Promise<void> => {
  const {
    title,
    subtitle,
    dateRange,
    kpis = [],
    tables = [],
    charts = [],
    footer = 'Generated by Lulu Intelligence Dashboard',
  } = options;

  const doc = new jsPDF('p', 'mm', 'a4');
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 15;
  let yPosition = margin;

  // Helper function to add page if needed
  const checkPageBreak = (requiredSpace: number) => {
    if (yPosition + requiredSpace > pageHeight - margin) {
      doc.addPage();
      yPosition = margin;
      return true;
    }
    return false;
  };

  // ===== HEADER =====
  // Header background
  doc.setFillColor(COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]);
  doc.rect(0, 0, pageWidth, 40, 'F');

  // Logo/Brand text
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(24);
  doc.setFont('helvetica', 'bold');
  doc.text('Lulu Intelligence', margin, 18);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text('UAE Analytics Dashboard', margin, 26);

  // Report title
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(title, margin, 35);

  // Date on right side
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  const dateStr = dateRange || new Date().toLocaleDateString('en-AE', {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  doc.text(dateStr, pageWidth - margin, 35, { align: 'right' });

  yPosition = 50;

  // ===== SUBTITLE =====
  if (subtitle) {
    doc.setTextColor(COLORS.lightText[0], COLORS.lightText[1], COLORS.lightText[2]);
    doc.setFontSize(10);
    doc.text(subtitle, margin, yPosition);
    yPosition += 10;
  }

  // ===== KPIs SECTION =====
  if (kpis.length > 0) {
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text('Key Performance Indicators', margin, yPosition);
    yPosition += 8;

    // KPI boxes
    const kpiWidth = (pageWidth - 2 * margin - (kpis.length - 1) * 5) / Math.min(kpis.length, 4);
    const kpiHeight = 25;
    
    const kpisPerRow = 4;
    const rows = Math.ceil(kpis.length / kpisPerRow);
    
    for (let row = 0; row < rows; row++) {
      checkPageBreak(kpiHeight + 10);
      
      const rowKpis = kpis.slice(row * kpisPerRow, (row + 1) * kpisPerRow);
      const actualKpiWidth = (pageWidth - 2 * margin - (rowKpis.length - 1) * 5) / rowKpis.length;
      
      rowKpis.forEach((kpi, index) => {
        const x = margin + index * (actualKpiWidth + 5);
        
        // KPI box background
        doc.setFillColor(COLORS.background[0], COLORS.background[1], COLORS.background[2]);
        doc.roundedRect(x, yPosition, actualKpiWidth, kpiHeight, 2, 2, 'F');
        
        // KPI label
        doc.setTextColor(COLORS.lightText[0], COLORS.lightText[1], COLORS.lightText[2]);
        doc.setFontSize(8);
        doc.setFont('helvetica', 'normal');
        doc.text(kpi.label, x + 5, yPosition + 7);
        
        // KPI value
        doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
        doc.setFontSize(14);
        doc.setFont('helvetica', 'bold');
        doc.text(String(kpi.value), x + 5, yPosition + 17);
        
        // KPI change indicator
        if (kpi.change) {
          const isPositive = kpi.change.includes('+') || !kpi.change.includes('-');
          doc.setTextColor(isPositive ? 34 : 220, isPositive ? 197 : 38, isPositive ? 94 : 38);
          doc.setFontSize(8);
          doc.text(kpi.change, x + actualKpiWidth - 5, yPosition + 17, { align: 'right' });
        }
      });
      
      yPosition += kpiHeight + 5;
    }
    
    yPosition += 5;
  }

  // ===== TABLES SECTION =====
  for (const table of tables) {
    checkPageBreak(40);
    
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(table.title, margin, yPosition);
    yPosition += 5;

    autoTable(doc, {
      startY: yPosition,
      head: [table.data.headers],
      body: table.data.rows,
      margin: { left: margin, right: margin },
      headStyles: {
        fillColor: [COLORS.primary[0], COLORS.primary[1], COLORS.primary[2]],
        textColor: [255, 255, 255],
        fontStyle: 'bold',
        fontSize: 9,
      },
      bodyStyles: {
        fontSize: 9,
        textColor: [COLORS.text[0], COLORS.text[1], COLORS.text[2]],
      },
      alternateRowStyles: {
        fillColor: [COLORS.background[0], COLORS.background[1], COLORS.background[2]],
      },
      styles: {
        cellPadding: 3,
        lineColor: [226, 232, 240],
        lineWidth: 0.1,
      },
    });

    yPosition = (doc as any).lastAutoTable.finalY + 10;
  }

  // ===== CHARTS SECTION =====
  for (const chart of charts) {
    const chartHeight = chart.height || 80;
    checkPageBreak(chartHeight + 20);
    
    doc.setTextColor(COLORS.text[0], COLORS.text[1], COLORS.text[2]);
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(chart.title, margin, yPosition);
    yPosition += 5;

    try {
      const chartWidth = chart.width || pageWidth - 2 * margin;
      doc.addImage(chart.imageData, 'PNG', margin, yPosition, chartWidth, chartHeight);
      yPosition += chartHeight + 10;
    } catch (error) {
      console.error('Error adding chart image:', error);
      doc.setTextColor(COLORS.lightText[0], COLORS.lightText[1], COLORS.lightText[2]);
      doc.setFontSize(10);
      doc.text('[Chart image not available]', margin, yPosition + 10);
      yPosition += 20;
    }
  }

  // ===== FOOTER =====
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    
    // Footer line
    doc.setDrawColor(226, 232, 240);
    doc.setLineWidth(0.5);
    doc.line(margin, pageHeight - 15, pageWidth - margin, pageHeight - 15);
    
    // Footer text
    doc.setTextColor(COLORS.lightText[0], COLORS.lightText[1], COLORS.lightText[2]);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text(footer, margin, pageHeight - 10);
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
    
    // Timestamp
    const timestamp = new Date().toLocaleString('en-AE');
    doc.text(`Generated: ${timestamp}`, pageWidth / 2, pageHeight - 10, { align: 'center' });
  }

  // Download the PDF
  const fileName = `${title.toLowerCase().replace(/\s+/g, '_')}_${new Date().toISOString().split('T')[0]}.pdf`;
  doc.save(fileName);
};

// Helper function to capture chart as image
export const captureChartAsImage = async (elementId: string): Promise<string | null> => {
  try {
    // @ts-ignore - html2canvas dynamic import
    const html2canvas = (await import('html2canvas')).default;
    const element = document.getElementById(elementId);
    if (!element) return null;
    
    const canvas = await html2canvas(element, {
      backgroundColor: '#1e293b',
      scale: 2,
    });
    
    return canvas.toDataURL('image/png');
  } catch (error) {
    console.error('Error capturing chart:', error);
    return null;
  }
};

// Pre-built export functions for specific pages
export const exportAnalyticsPDF = async (
  kpis: { totalSales: number; totalTransactions: number; avgBasketSize: number; conversionRate: number; salesGrowth: number; topCategory: string },
  salesData: { date: string; sales: number; transactions: number }[],
  categoryData: { category: string; sales: number; percentage: number }[],
  dateRange: string
) => {
  await generatePDF({
    title: 'Analytics Dashboard Report',
    subtitle: 'Deep insights into sales performance and trends',
    dateRange: `Report Period: ${dateRange === '7d' ? 'Last 7 Days' : dateRange === '30d' ? 'Last 30 Days' : 'Last 90 Days'}`,
    kpis: [
      { label: 'Total Sales', value: `AED ${(kpis.totalSales / 1000).toFixed(0)}K`, change: `+${kpis.salesGrowth}%` },
      { label: 'Transactions', value: kpis.totalTransactions.toLocaleString(), change: '+8.2%' },
      { label: 'Avg Basket', value: `AED ${kpis.avgBasketSize}`, change: '+3.5%' },
      { label: 'Conversion', value: `${kpis.conversionRate}%`, change: '+2.1%' },
      { label: 'Top Category', value: kpis.topCategory },
      { label: 'Active Stores', value: '10' },
    ],
    tables: [
      {
        title: 'Daily Sales Trend',
        data: {
          headers: ['Date', 'Sales (AED)', 'Transactions', 'Avg Basket'],
          rows: salesData.map(d => [d.date, d.sales.toLocaleString(), d.transactions.toLocaleString(), Math.round(d.sales / d.transactions).toLocaleString()]),
        },
      },
      {
        title: 'Category Distribution',
        data: {
          headers: ['Category', 'Sales (AED)', 'Percentage'],
          rows: categoryData.map(c => [c.category, c.sales.toLocaleString(), `${c.percentage}%`]),
        },
      },
    ],
  });
};

export const exportReportsPDF = async (
  kpis: { totalSales: number; totalTransactions: number; avgBasketSize: number; salesGrowth: number },
  salesTrend: { date: string; sales: number; transactions: number }[],
  categorySales: { category: string; sales: number; percentage: number }[],
  storeSales: { store_name: string; location: string; sales: number; growth: number }[],
  topItems: { item_name: string; category: string; total_sales: number; quantity: number }[],
  dateRange: string
) => {
  await generatePDF({
    title: 'Sales & Performance Report',
    subtitle: 'Comprehensive sales analytics and performance metrics',
    dateRange: `Report Period: ${dateRange === '7d' ? 'Last 7 Days' : dateRange === '30d' ? 'Last 30 Days' : dateRange === '90d' ? 'Last 90 Days' : 'Year to Date'}`,
    kpis: [
      { label: 'Total Sales', value: `AED ${kpis.totalSales.toLocaleString()}`, change: kpis.salesGrowth >= 0 ? `+${kpis.salesGrowth.toFixed(1)}%` : `${kpis.salesGrowth.toFixed(1)}%` },
      { label: 'Transactions', value: kpis.totalTransactions.toLocaleString() },
      { label: 'Avg Basket Size', value: `AED ${kpis.avgBasketSize.toLocaleString()}` },
      { label: 'Active Stores', value: '10' },
    ],
    tables: [
      {
        title: 'Daily Sales Trend',
        data: {
          headers: ['Date', 'Sales (AED)', 'Transactions'],
          rows: salesTrend.map(d => [d.date, d.sales.toLocaleString(), d.transactions.toLocaleString()]),
        },
      },
      {
        title: 'Sales by Category',
        data: {
          headers: ['Category', 'Sales (AED)', 'Share'],
          rows: categorySales.map(c => [c.category, c.sales.toLocaleString(), `${c.percentage}%`]),
        },
      },
      {
        title: 'Store Performance',
        data: {
          headers: ['Store', 'Location', 'Sales (AED)', 'Growth'],
          rows: storeSales.map(s => [s.store_name, s.location, s.sales.toLocaleString(), `${s.growth >= 0 ? '+' : ''}${s.growth}%`]),
        },
      },
      {
        title: 'Top Selling Items',
        data: {
          headers: ['Item', 'Category', 'Total Sales (AED)', 'Quantity'],
          rows: topItems.map(i => [i.item_name, i.category, i.total_sales.toLocaleString(), i.quantity.toLocaleString()]),
        },
      },
    ],
  });
};
